baseURL = "http://localhost:1313/"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
theme = "jane"
title = "Jane - A super concise theme for Hugo"
[Languages.en]
copyright = ""
disqusShortname = ""
googleAnalytics = ""
hasCJKLanguage = true
languageCode = "en"
paginate = 3
rssLimit = 20
[author]
name = "xianmin"
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4
[[menu.main]]
name = "external-link"
url = "https://gohugo.io"
weight = 6
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 5
[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/post/"
weight = 3
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 2
[params]
archive-paginate = 3
autocollapsetoc = false
baidu_analytics = ""
baidu_push = false
baidu_verification = ""
bootcdn = false
changyanappid = ""
changyanappkey = ""
contentcopyright = "<a rel=\"license noopener\" href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/\" target=\"_blank\">CC BY-NC-ND 4.0</a>"
customcss = []
customjs = []
dateformattouse = "2006-01-02T00:00:00+00:00"
debug = false
description = "Hugo theme jane example site."
fancybox = true
google_verification = ""
homefullcontent = false
keywords = ["Hugo", "theme", "jane"]
logotitle = "Jane"
mathjax = false
moremeta = true
rssfullcontent = true
since = "2017"
tencent_analytics = ""
toc = true
[params.gitment]
clientid = ""
clientsecret = ""
owner = ""
repo = ""
[params.publiccdn]
enable = false
fancyboxcss = "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css\" integrity=\"sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=\" crossorigin=\"anonymous\">"
fancyboxjs = "<script src=\"https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js\" integrity=\"sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=\" crossorigin=\"anonymous\"></script>"
gitmentcss = "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css\" crossorigin=\"anonymous\">"
gitmentjs = "<script src=\"https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js\" crossorigin=\"anonymous\"></script>"
jquery = "<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js\" integrity=\"sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=\" crossorigin=\"anonymous\"></script>"
slideout = "<script src=\"https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js\" integrity=\"sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=\" crossorigin=\"anonymous\"></script>"
[params.reward]
alipay = "/path/to/your/alipay-qr-code.png"
enable = false
wechat = "/path/to/your/wechat-qr-code.png"
[params.social]
a-email = "mailto:your@email.com"
b-stack-overflow = "http://localhost:1313"
c-twitter = "http://localhost:1313"
d-facebook = "http://localhost:1313"
e-linkedin = "http://localhost:1313"
f-google = "http://localhost:1313"
g-github = "http://localhost:1313"
h-weibo = "http://localhost:1313"
i-zhihu = "http://localhost:1313"
j-douban = "http://localhost:1313"
k-pocket = "http://localhost:1313"
l-tumblr = "http://localhost:1313"
m-instagram = "http://localhost:1313"
n-gitlab = "http://en.xianmin.org/hugo-theme-jane/"
o-goodreads = "http://en.xianmin.org/hugo-theme-jane/"
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
